all:
	gcc -c tad_vetor.c -o tad_vetor.o
	gcc main.c tad_vetor.o -o main
	./main

clean:
	rm main
	rm *.o


teste1: 
	gcc -c tad_vetor.c -o tad_vetor.o
	gcc teste1.c tad_vetor.o -o main
	./main

teste2: 
	gcc -c tad_vetor.c -o tad_vetor.o
	gcc teste2.c tad_vetor.o -o main
	./main